# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.srcs/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0.xci
# IP: The module: 'processing_system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.gen/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.gen/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.gen/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.srcs/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0.xci
# IP: The module: 'processing_system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.gen/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.gen/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/adc_test_2/adc_test_2.gen/sources_1/bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
