# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
# IP: The module: 'system_rst_ps7_0_125M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
# IP: The module: 'system_rst_ps7_0_125M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aidan/Downloads/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
