# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adc.xdc

# XDC: new/led.xdc

# Block Designs: bd/processing_system/processing_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system || ORIG_REF_NAME==processing_system} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_proc_sys_reset_0_0 || ORIG_REF_NAME==processing_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_processing_system7_0_0/processing_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_processing_system7_0_0 || ORIG_REF_NAME==processing_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_axi_dma_4/processing_system_axi_dma_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_axi_dma_4 || ORIG_REF_NAME==processing_system_axi_dma_4} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_adc_to_axis_0_0/processing_system_adc_to_axis_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_adc_to_axis_0_0 || ORIG_REF_NAME==processing_system_adc_to_axis_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_ps7_0_axi_periph_6/processing_system_ps7_0_axi_periph_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_ps7_0_axi_periph_6 || ORIG_REF_NAME==processing_system_ps7_0_axi_periph_6} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_xlconcat_0_0/processing_system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_xlconcat_0_0 || ORIG_REF_NAME==processing_system_xlconcat_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_xbar_0/processing_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_xbar_0 || ORIG_REF_NAME==processing_system_xbar_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_axi_interconnect_0_0/processing_system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_axi_interconnect_0_0 || ORIG_REF_NAME==processing_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_auto_pc_0/processing_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_auto_pc_0 || ORIG_REF_NAME==processing_system_auto_pc_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_s00_data_fifo_0/processing_system_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_s00_data_fifo_0 || ORIG_REF_NAME==processing_system_s00_data_fifo_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_s01_data_fifo_0/processing_system_s01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_s01_data_fifo_0 || ORIG_REF_NAME==processing_system_s01_data_fifo_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_s02_data_fifo_0/processing_system_s02_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_s02_data_fifo_0 || ORIG_REF_NAME==processing_system_s02_data_fifo_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_auto_pc_1/processing_system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_auto_pc_1 || ORIG_REF_NAME==processing_system_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/adc_to_ps/adc_to_ps.gen/sources_1/bd/processing_system/processing_system_ooc.xdc
