# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adc.xdc

# XDC: new/led.xdc

# Block Designs: bd/processing_system/processing_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system || ORIG_REF_NAME==processing_system} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_proc_sys_reset_0_0/processing_system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_proc_sys_reset_0_0 || ORIG_REF_NAME==processing_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_processing_system7_0_0/processing_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_processing_system7_0_0 || ORIG_REF_NAME==processing_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_top_0_1/processing_system_top_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_top_0_1 || ORIG_REF_NAME==processing_system_top_0_1} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_axi_gpio_0_0/processing_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_axi_gpio_0_0 || ORIG_REF_NAME==processing_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_ps7_0_axi_periph_7/processing_system_ps7_0_axi_periph_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_ps7_0_axi_periph_7 || ORIG_REF_NAME==processing_system_ps7_0_axi_periph_7} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_auto_pc_0/processing_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_auto_pc_0 || ORIG_REF_NAME==processing_system_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/aidan/Portfolio/FPGA Designs/adc_to_ps_2/adc_to_ps_2.gen/sources_1/bd/processing_system/processing_system_ooc.xdc
