# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aidan/Portfolio/FPGA Designs/BRAM_Test_3/BRAM_Test_3.srcs/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
# IP: The module: 'system_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/BRAM_Test_3/BRAM_Test_3.gen/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/aidan/Portfolio/FPGA Designs/BRAM_Test_3/BRAM_Test_3.srcs/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
# IP: The module: 'system_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aidan/Portfolio/FPGA Designs/BRAM_Test_3/BRAM_Test_3.gen/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
